[package]
name = "tor-parse"
version = "0.1.0"
authors = ["D Keeler <mozkeeler@gmail.com>"]
license = "MPL-2.0"

[dependencies]
hex = "0.3.1"
curve25519-dalek = "^0.14"
hmac = "0.5.0"
sha2 = "0.7.0"
rust-crypto = "^0.2"
